// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-site-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/content.ts
var overview = {
  name: "NUDLE",
  tagline: "Smarter Learning. Connected Minds.",
  description: "NUDLE empowers educators and institutions with AI-driven tools for teaching, assessment, and learning analytics.",
  stats: [
    { label: "Students", value: "10K+" },
    { label: "Institutions", value: "500+" },
    { label: "Satisfaction", value: "98%" },
    { label: "Rating", value: "4.9/5 from 10,000+ educators" }
  ],
  primaryCtas: ["Get Started Free", "Watch Demo", "Request a Demo"]
};
var features = [
  {
    title: "AI-Powered Insights",
    description: "Leverage artificial intelligence to gain deep insights into student performance and learning patterns."
  },
  {
    title: "Real-Time Analytics",
    description: "Track progress and performance metrics with comprehensive dashboards and reporting tools."
  },
  {
    title: "Collaborative Learning",
    description: "Foster collaboration between students, educators, and institutions with integrated communication tools."
  },
  {
    title: "Instant Feedback",
    description: "Provide immediate feedback to students with automated assessment and grading systems."
  },
  {
    title: "Secure & Compliant",
    description: "Enterprise-grade security with full compliance to educational data protection standards."
  },
  {
    title: "Rich Content Library",
    description: "Access thousands of curriculum-aligned resources and learning materials."
  }
];
var audiences = {
  institutions: {
    headline: "Transform Your Institution with AI",
    summary: "Streamline operations, enhance teaching effectiveness, and improve student outcomes with a comprehensive platform.",
    benefits: [
      "Centralized dashboard for all school operations",
      "Real-time student performance analytics",
      "Automated administrative workflows",
      "Secure data management and compliance",
      "Customizable reporting and insights",
      "Integration with existing systems"
    ],
    cta: "Request a Demo"
  },
  students: {
    headline: "Your Personal AI Learning Assistant",
    summary: "Experience personalized learning powered by artificial intelligence.",
    benefits: [
      "Personalized Learning \u2014 AI adapts to your learning style and pace",
      "Goal Tracking \u2014 set and achieve your academic goals",
      "Progress Insights \u2014 visualize your learning journey",
      "24/7 AI Assistance \u2014 get help whenever you need it"
    ],
    cta: "Start Learning for Free"
  }
};
var testimonials = [
  {
    quote: "NUDLE has transformed how we teach and assess students. The AI insights are incredible and have helped us identify learning gaps early.",
    author: "Dr. Sarah Johnson",
    role: "Department Head",
    institution: "Stanford University"
  },
  {
    quote: "The analytics dashboard gives us real-time visibility into student performance across all programs. It's become essential to our operations.",
    author: "Michael Chen",
    role: "Dean of Students",
    institution: "MIT"
  },
  {
    quote: "As a student, having an AI assistant that understands my learning style has been game-changing. My grades have improved significantly.",
    author: "Emily Rodriguez",
    role: "Undergraduate Student",
    institution: "Harvard University"
  }
];

// src/lib/mcp/tools/get-site-overview.ts
var get_site_overview_default = defineTool({
  name: "get_site_overview",
  title: "Get site overview",
  description: "Get NUDLE's positioning: product name, tagline, description, headline stats, and primary calls to action.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
    structuredContent: overview
  })
});

// src/lib/mcp/tools/list-features.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_features_default = defineTool2({
  name: "list_features",
  title: "List platform features",
  description: "List NUDLE's platform features with descriptions. Optionally filter by a keyword matched against the title and description.",
  inputSchema: {
    query: z.string().trim().optional().describe("Optional keyword to filter features, e.g. 'analytics'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.toLowerCase();
    const items = q ? features.filter(
      (f) => f.title.toLowerCase().includes(q) || f.description.toLowerCase().includes(q)
    ) : features;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { features: items }
    };
  }
});

// src/lib/mcp/tools/get-audience-benefits.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_audience_benefits_default = defineTool3({
  name: "get_audience_benefits",
  title: "Get audience benefits",
  description: "Get NUDLE's value proposition for a specific audience: institutions or students.",
  inputSchema: {
    audience: z2.enum(["institutions", "students"]).describe("Which audience to describe.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ audience }) => {
    const data = audiences[audience];
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { audience, ...data }
    };
  }
});

// src/lib/mcp/tools/list-testimonials.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_testimonials_default = defineTool4({
  name: "list_testimonials",
  title: "List testimonials",
  description: "List public customer testimonials shown on the NUDLE site, with author, role, and institution.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(testimonials, null, 2) }],
    structuredContent: { testimonials }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "nudle-ai-landing",
  title: "Nudle AI Landing",
  version: "0.1.0",
  instructions: "Public tools for the NUDLE AI learning platform landing page. Use `get_site_overview` for positioning and stats, `list_features` for platform capabilities, `get_audience_benefits` for institution or student value props, and `list_testimonials` for customer quotes.",
  tools: [
    get_site_overview_default,
    list_features_default,
    get_audience_benefits_default,
    list_testimonials_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
