import { Link, useSearchParams } from "react-router-dom";
import { CheckCircle2, Clock, Download, Printer, XCircle } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@nudle/ui/button";
import { cn } from "@/lib/utils";

type PaymentStatus = "success" | "pending" | "failed";

const config = {
  success: {
    icon: CheckCircle2,
    label: "Payment successful",
    tone: "bg-primary/10 text-primary",
    blurb: "The funds have been paid into the school account.",
  },
  pending: {
    icon: Clock,
    label: "Payment pending",
    tone: "bg-muted text-muted-foreground",
    blurb: "We are waiting for the transfer to clear. This can take up to 24 hours.",
  },
  failed: {
    icon: XCircle,
    label: "Payment failed",
    tone: "bg-destructive/10 text-destructive",
    blurb: "The payment was not completed. No money has left your account.",
  },
} as const;

export default function FinanceReceipt() {
  const [params] = useSearchParams();
  const statusRaw = params.get("status") ?? "success";
  const status: PaymentStatus = ["success", "pending", "failed"].includes(statusRaw)
    ? (statusRaw as PaymentStatus)
    : "success";

  const receipt = useMemo(
    () => ({
      ref: params.get("ref") ?? "—",
      status,
      amount: Number(params.get("amount") ?? 0),
      fee: Number(params.get("fee") ?? 0),
      method: params.get("method") ?? "—",
      school: params.get("school") ?? "—",
      account: params.get("account") ?? "—",
      purpose: params.get("purpose") ?? "—",
      date: params.get("date") ?? new Date().toISOString(),
    }),
    [params, status],
  );

  const meta = config[receipt.status];
  const Icon = meta.icon;
  const total = Math.round((receipt.amount + receipt.fee) * 100) / 100;
  const when = new Date(receipt.date);
  const dateLabel = Number.isNaN(when.getTime()) ? receipt.date : when.toLocaleString();

  const rows: Array<[string, string]> = [
    ["Reference", receipt.ref],
    ["Status", meta.label],
    ["Date", dateLabel],
    ["School", receipt.school],
    ["School account", receipt.account],
    ["Purpose", receipt.purpose],
    ["Method", receipt.method],
    ["Amount", `$${receipt.amount.toFixed(2)}`],
    ["Processing fee", `$${receipt.fee.toFixed(2)}`],
    ["Total", `$${total.toFixed(2)}`],
  ];

  const [verifyUrl, setVerifyUrl] = useState("");
  useEffect(() => {
    setVerifyUrl(window.location.href);
  }, []);

  function download() {
    const body = [
      "KLEVA FINANCE — PAYMENT RECEIPT",
      "Powered by Blue Finance",
      "".padEnd(40, "-"),
      ...rows.map(([k, v]) => `${k.padEnd(18)}${v}`),
      "".padEnd(40, "-"),
      `Verify at: ${verifyUrl}`,
      "This receipt was generated by Kleva Finance.",
    ].join("\n");
    const url = URL.createObjectURL(new Blob([body], { type: "text/plain;charset=utf-8" }));
    const a = document.createElement("a");
    a.href = url;
    a.download = `kleva-receipt-${receipt.ref}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="mx-auto max-w-xl">
      <div className="rounded-2xl border border-border bg-card p-8 shadow-sm print:shadow-none">
        <div className="flex flex-col items-center text-center">
          <span className={cn("flex h-14 w-14 items-center justify-center rounded-full", meta.tone)}>
            <Icon className="h-7 w-7" />
          </span>
          <h1 className="mt-5 text-xl font-semibold text-foreground">{meta.label}</h1>
          <p className="mt-2 text-sm text-muted-foreground">{meta.blurb}</p>
          <p className="mt-4 text-3xl font-semibold text-foreground">${total.toFixed(2)}</p>
        </div>

        <dl className="mt-8 space-y-2 rounded-xl bg-muted/50 p-4 text-sm">
          {rows.map(([k, v]) => (
            <div key={k} className="flex items-start justify-between gap-4">
              <dt className="text-muted-foreground">{k}</dt>
              <dd className="text-right font-medium break-all text-foreground">{v}</dd>
            </div>
          ))}
        </dl>

        <div className="mt-6 flex flex-col items-center gap-3 rounded-xl border border-border p-5 text-center">
          <div className="rounded-lg bg-white p-3">
            {verifyUrl ? (
              <QRCodeSVG value={verifyUrl} size={132} level="M" />
            ) : (
              <div className="h-[132px] w-[132px] animate-pulse rounded bg-muted" />
            )}
          </div>
          <p className="text-sm font-medium text-foreground">Scan to verify this payment</p>
          <p className="text-xs text-muted-foreground">
            Reference {receipt.ref} · the school can scan this code to confirm the receipt is genuine.
          </p>
        </div>

        <div className="mt-8 grid gap-2 sm:grid-cols-2 print:hidden">
          <Button className="rounded-full" onClick={download}>
            <Download className="mr-2 h-4 w-4" />
            Download receipt
          </Button>
          <Button variant="outline" className="rounded-full" onClick={() => window.print()}>
            <Printer className="mr-2 h-4 w-4" />
            Print / save as PDF
          </Button>
        </div>

        <div className="mt-2 flex flex-col gap-2 print:hidden">
          {receipt.status === "failed" && (
            <Button asChild variant="secondary" className="rounded-full">
              <Link to="/finance/pay">Try the payment again</Link>
            </Button>
          )}
          <Button asChild variant="ghost" className="rounded-full">
            <Link to="/finance/home">Back to Kleva Finance</Link>
          </Button>
        </div>
      </div>
    </div>
  );
}
